### ISSUE TITLE
java二进制相关基础链接错误

### ISSUE THREAD

**Issue by zane-rl** [lirenzuo/rocketmq-rocketmq-all-4.1.0-incubating#1]
应该是这个:https://mp.weixin.qq.com/s/AIvthkKEqacnfZBIZAxSKA

**Comment by jiangxinlingdu** [comment]
不是错误，是这样设置的，（关注匠心零度公众号进行获取）

**Comment by zane-rl** [comment]
哇！竟然还有回复。我知道公众号里面有，但是有时候在pc上看方面，关键是我可以收藏，嘿嘿
